/**
 * CTA URLs for payment and intake buttons.
 */
export const LINKS = {
  FAILED_PAYMENT_PAYMENT_LINK: "FAILED_PAYMENT_PAYMENT_LINK_PLACEHOLDER",
  FAILED_PAYMENT_INTAKE_FORM: "FAILED_PAYMENT_INTAKE_FORM_PLACEHOLDER",
} as const;
